### ISSUE TITLE
[Blog] Migrate old posts from WordPress to Markdown

### ISSUE THREAD

**Issue by HRemonen** [HRemonen/hremonen-site#17]
The old posts must be transferred someway from WordPress to Markdown files.

--- 

- [x] Find a way to automatically do the Migration
- [x] Fix code highlighting
- [x] Add post images into cloudinary and fix image sources
- [x] Find a way to display videos -- Maybe needs another rehype plugin?
- [x] Add missing cover images to posts without them
