### ISSUE TITLE
[Blog] Blog post page

### ISSUE THREAD

**Issue by HRemonen** [HRemonen/hremonen-site#18]
The single post page is now lacking alot of features I want to bring in. Currently it has some basic styles from the Tailwind typography plugin and basic functionality. However there is alot of things to implement.

---

- [x] Add post metadata to the start of the page along with the cover image
- [x] Allow for raw HTML in Markdown -- this is for videos mostly
- [x] At the bottom of the page suggest similar posts around the same keywords or categories -- for this some kind of algorithm needs to be implemented
- [x] #14
